# Generated by Django 3.1.4 on 2021-01-10 12:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(default=datetime.datetime(2021, 1, 10, 12, 9, 5, 807755, tzinfo=utc))),
                ('Text', models.CharField(max_length=1000)),
                ('Words', models.IntegerField()),
                ('Nums', models.IntegerField()),
                ('Author', models.CharField(max_length=256)),
            ],
        ),
    ]
