# Generated by Django 3.1.4 on 2021-01-10 12:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_strhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strhistory',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 10, 12, 50, 13, 469058, tzinfo=utc)),
        ),
    ]
