# Generated by Django 3.1.6 on 2021-03-01 15:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_auto_20210301_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
